### ISSUE TITLE
Installation on WIndows

### ISSUE THREAD

**Issue by deeplearning-ai-research** [01org/daal#1]
Hi,

In this page, only C++/Java setup is explained.
https://software.intel.com/en-us/get-started-with-daal-for-windows

In this one, only Linux one.
https://software.intel.com/en-us/articles/how-to-install-the-python-version-of-intel-daal-in-linux

Would it be possible to get some details for Windows platform and Python install ?

Thanks

**Comment by iburyl** [comment]
Hi,

Python interfaces are not part of Intel DAAL package on GitHub.

The instruction you see for Linux should work with minor modification on Windows as well. On Windows side we support Python 3.5 only, though. If you have problems with that, tell us and we will try to help. We will update in-details instruction to include Windows part.

There are other options for getting Python interfaces as well. See this article for details:
https://software.intel.com/en-us/articles/how-to-install-the-python-version-of-intel-data-analytics-acceleration-library-intel-daal

**Comment by avineet4** [comment]
## Bug Report: Data corruption in PrimitiveCollection::reallocate() copy logic

**Describe the bug**
The `PrimitiveCollection::reallocate()` method has reversed copy logic that causes complete data corruption when the `copy` parameter is set to `true`.

**To Reproduce**
Steps to reproduce the behavior:
1. Create a PrimitiveCollection with some data
2. Call `reallocate(new_size, copy=true)` 
3. Observe that all data is lost/corrupted

**Expected behavior**
The method should preserve existing data by copying from the old buffer to the new buffer.

**Buggy Code Location**
File: `cpp/daal/include/services/internal/collection.h:76-79`

```cpp
if (copy)
{
    for (size_t i = 0; i < _size; i++)
    {
        _buffer[i] = buffer[i];  // ❌ BUG: Copies garbage FROM new TO old
    }
}
```

**Root Cause**
- `_buffer` = old buffer (contains user data)
- `buffer` = new buffer (uninitialized/garbage data)
- Current code copies garbage FROM new buffer TO old buffer
- Then `destroy()` frees the old buffer (now containing garbage)
- Result: All data lost

**Impact**
- **Severity**: HIGH (complete data loss)
- **Status**: Dormant (no current usage with copy=true found)
- **Risk**: Dangerous footgun for future developers

**Proposed Fix**
```cpp
if (copy)
{
    const size_t copy_count = (size < _size) ? size : _size;
    for (size_t i = 0; i < copy_count; i++)
    {
        buffer[i] = _buffer[i];  // ✅ Copy FROM old TO new
    }
}
```

**Environment:**
- OS: All platforms
- Compiler: All supported compilers
- Version: All versions (historical bug)

**Comment by avineet4** [comment]
## Bug Report: Buffer copy direction and overrun prevention in PrimitiveCollection

**Issue Summary**
Fixed critical bug in `PrimitiveCollection::reallocate()` method that had reversed copy logic and potential buffer overrun vulnerability.

**Bug Details**
- **File**: `cpp/daal/include/services/internal/collection.h`
- **Method**: `PrimitiveCollection::reallocate()`
- **Lines**: 76-82

**Problems Fixed**
1. **Reversed Copy Direction**: Original code copied from uninitialized new buffer to old buffer containing user data
2. **Buffer Overrun**: No bounds checking when copying data between buffers of different sizes

**Original Buggy Code**
```cpp
if (copy)
{
    for (size_t i = 0; i < _size; i++)
    {
        _buffer[i] = buffer[i];  // ❌ Copies garbage TO user data
    }
}
```

**Fixed Code**
```cpp
if (copy)
{
    // Copy data from old buffer to new buffer, preserving existing data
    // Use min of old and new size to prevent buffer overrun
    const size_t copy_count = (size < _size) ? size : _size;
    for (size_t i = 0; i < copy_count; i++)
    {
        buffer[i] = _buffer[i];  // ✅ Copy FROM old TO new
    }
}
```

**Impact**
- **Severity**: HIGH (data corruption and potential security vulnerability)
- **Scope**: All platforms and compilers
- **Status**: Fixed in branch `bugfix/primitive-collection-copy-logic`

**Testing**
- Verified fix preserves existing data correctly
- Confirmed bounds checking prevents buffer overrun
- No regressions in existing functionality
