### ISSUE TITLE
Machine Learning Algorithm User Inputs

### ISSUE THREAD

**Issue by vibhatha** [01org/daal#35]
Hi,

I am trying to use PCA and MLR for my project. I want to learn how to add the number of iterations, number of principal components, step size and such parameters to the program initialization. Is there any way to do this ?

If it is could you please guide me how to set them in specific classes in DAAL Java source code. Thanks a lot for your time.

**Comment by RuslanIsrafilov** [comment]
Instead PCA returns eigenvalues and eigenvectors of covariance matrix obtained from the data (have a look at the [example](01org/daal/blob/daal_2018_beta_update1/examples/java/com/intel/daal/examples/pca/PCACorDenseBatch.java)).  You can use them in order to reduce dimensionality of your data, i.e. apply PCA transformation on your side by picking required number of eigenvectors. We are planning to support PCA transformation in one of the future releases. 

> I want to learn how to add the number of iterations, ... step size

Internally DAAL relies on **direct** algorithms to solve a system of linear equations, an eigenvalues problem or finding inverse/pseudoinverse of a matrix (by calling LAPACK), so we can't provide parameters like *number of iterations* for PCA or linear regression, because we just don't have them in implementation and can't adjust in LAPACK.

**Comment by vibhatha** [comment]
Yes I understand, will it be available in future versions ?

**Comment by RuslanIsrafilov** [comment]
We may consider adding iterative linear regression algorithm based on stochastic gradient descent (SGD). Are you interested in such algorithm?

**Comment by vibhatha** [comment]
Yes of course, I think it is easier when we have the ability to change the input parameters in all machine learning algorithms. When it comes to evaluating practical scenarios, tuning those values can bring more accurate results. That is why I am very much interested in such applications. And also the customized optimization methods, kernels like (RBF, Linear) or for instance stochastic or batch gradient descent selection as an input parameter would do a wide range of experiments. I think adding such algorithms with user customization would bring a broad crowd to use the tool. And thanks a lot for helping me out.

**Comment by RuslanIsrafilov** [comment]
@vibhatha, currently DAAL allows to use SGD + LR, but there is no single algorithm which encapsulates all the logic, please find the example [here](https://github.com/01org/daal/blob/daal_2018_beta_update1/examples/java/com/intel/daal/examples/optimization_solvers/SGDDenseBatch.java).
